Hw patterns
kirillparaschenko/SaucedemoTests pull request #1
Opened 2023-05-20 17:43 UTC by kirillparaschenko

Completed home task. Applied patterns:
1. Chain Of Invocations
2. Loadable Page
3. Value of Objects
4. Builder

There is a problem when integrating with Core. Launch was implemented in BaseTest. Error occurs during build : 
Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute	Tests	C:\Users\kparaschenko\source\repos\SaucedemoTests\obj\Debug\net6.0\Tests.AssemblyInfo.cs	14	Active
thinking is related to experiments with Core.

![image](https://github.com/kirillparaschenko/SaucedemoTests/assets/92506072/91f894b0-8f7a-40b2-a82c-3867037b4643)

2023-05-20 19:05 UTC, wildpioneer requested changes

2023-05-20 19:05 UTC, wildpioneer commented on Tests/OrderingTests.cs
> +            Assert.IsTrue(new CheckoutCompletePage(ChromeDriver).IsPageOpened());
Является ли проверка, что CheckoutCompletePage открыта, достаточным условием успешной покупки?

2023-05-20 19:05 UTC, wildpioneer commented on Tests/OrderingTests.cs
> +            UserBuilder userBuilder = new UserBuilder();
Builder как раз используется без двойной инициализации.
            User user = new UserBuilder()
                .SetUserName("standard_user")
                .SetPassword("secret_sauce")
                .SetUserFirstName("username")
                .SetUserLastName("username")
                .SetUserPostalCode("123456")
                .Build();

2023-05-20 19:05 UTC, wildpioneer commented on Tests/BaseTest.cs
> +            ChromeDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
Всего 5 секунд?

2023-05-20 19:05 UTC, wildpioneer commented on Tests/BaseTest.cs
> +            ChromeDriver = new ChromeDriver();
У тебя есть Browser класс - но ты инициализируешь ChromeDriver

2023-05-22 14:49 UTC, kirillparaschenko commented on Tests/OrderingTests.cs
> +            Assert.IsTrue(new CheckoutCompletePage(ChromeDriver).IsPageOpened());
Вообще недостатчно. По хорошему, нужно выполнить запрос и проверить, что заказ сохранился в базе данных, либо в контейнере.
Тут в методе IsPageOpened() есть проверка отображён ли контейнер с подверждением заказа, и если его не будет, то тест упадёт.
`        public override bool IsPageOpened()
        {
            try
            {
                return Driver.FindElement(CompleteTextLocator).Displayed;
            }
            catch (Exception e)
            {
                return false;
            }
        }`

2023-05-22 14:58 UTC, kirillparaschenko commented on Tests/BaseTest.cs
> +            ChromeDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
Да, неявное ожидание 5 секунд. Вряд ли на этом сайте какой-то элемент будет прогружаться более 5 секунд.

2023-05-22 15:26 UTC, kirillparaschenko commented on Tests/BaseTest.cs
> +            ChromeDriver = new ChromeDriver();
Поменял инитиализацию ChromeDriver в BaseTest, а также поменял конструкторы страниц , чтобы принимали не WebDriver, а интерфейс IWebDriver, но с разницей пока не разобрался, как и со структурой Core.

2023-06-05 17:41 UTC, wildpioneer commented
Проверено

2023-06-05 17:41 UTC, closed without merging